export const LOGIN = 'Login';
export const MOT_DE_PASSE_OUBLIE = 'Mot de passe oublié';

export const TRY_LOGIN = 'TRY_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const TRY_SIGNUP = 'TRY_SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const UPDATE_CURRENT_ROLE = 'UPDATE_CURRENT_ROLE';

export const LOGOUT = 'LOGOUT';

export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';

export const SET_LOADING = "SET_LOADING";
export const SET_MENU_EXPANDED = "SET_MENU_EXPANDED";
export const SET_MENU_ACTIVE_ITEM = "SET_MENU_ACTIVE_ITEM";

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const RESET_USER_PASSWORD_REQUEST = 'RESET_USER_PASSWORD_REQUEST';
export const RESET_USER_PASSWORD_SUCCESS = 'RESET_USER_PASSWORD_SUCCESS';
export const RESET_USER_PASSWORD_FAIL = 'RESET_USER_PASSWORD_FAIL';
