export const GET_INVOICES_REQUEST = 'GET_INVOICES_REQUEST';
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';
export const GET_INVOICES_FAIL = 'GET_INVOICES_FAIL';

export const ADD_INVOICE_REQUEST = 'ADD_INVOICE_REQUEST';
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS';
export const ADD_INVOICE_FAIL = 'ADD_INVOICE_FAIL';

export const ADD_INVOICES_MASSIVELY_REQUEST = 'ADD_INVOICES_MASSIVELY_REQUEST';
export const ADD_INVOICES_MASSIVELY_SUCCESS = 'ADD_INVOICES_MASSIVELY_SUCCESS';
export const ADD_INVOICES_MASSIVELY_FAIL = 'ADD_INVOICES_MASSIVELY_FAIL';

export const GET_INVOICE_REQUEST = 'GET_INVOICE_REQUEST';
export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';
export const GET_INVOICE_FAIL = 'GET_INVOICE_FAIL';

export const DELETE_INVOICE_REQUEST = 'DELETE_INVOICE_REQUEST';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_FAIL = 'DELETE_INVOICE_FAIL';

export const GET_ACTIVITIES_REQUEST = 'GET_ACTIVITIES_REQUEST';
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS';
export const GET_ACTIVITIES_FAIL = 'GET_ACTIVITIES_FAIL';

export const SET_INVOICE = 'SET_INVOICE';
export const SET_INVOICES = 'SET_INVOICES';