export const GET_PACKS_REQUEST = 'GET_PACKS_REQUEST';
export const GET_PACKS_SUCCESS = 'GET_PACKS_SUCCESS';
export const GET_PACKS_FAIL = 'GET_PACKS_FAIL';

export const ADD_PACK_REQUEST = 'ADD_PACK_REQUEST';
export const ADD_PACK_SUCCESS = 'ADD_PACK_SUCCESS';
export const ADD_PACK_FAIL = 'ADD_PACK_FAIL';

export const ADD_PACKS_MASSIVELY_REQUEST = 'ADD_PACKS_MASSIVELY_REQUEST';
export const ADD_PACKS_MASSIVELY_SUCCESS = 'ADD_PACKS_MASSIVELY_SUCCESS';
export const ADD_PACKS_MASSIVELY_FAIL = 'ADD_PACKS_MASSIVELY_FAIL';

export const GET_PACK_REQUEST = 'GET_PACK_REQUEST';
export const GET_PACK_SUCCESS = 'GET_PACK_SUCCESS';
export const GET_PACK_FAIL = 'GET_PACK_FAIL';

export const DELETE_PACK_REQUEST = 'DELETE_PACK_REQUEST';
export const DELETE_PACK_SUCCESS = 'DELETE_PACK_SUCCESS';
export const DELETE_PACK_FAIL = 'DELETE_PACK_FAIL';


export const SET_PACK = 'SET_PACK';