export const GET_STATISTICS_REQUEST = 'GET_STATISTICS_REQUEST';
export const GET_STATISTICS_SUCCESS = 'GET_STATISTICS_SUCCESS';
export const GET_STATISTICS_FAIL = 'GET_STATISTICS_FAIL';

export const GET_DASHBOARD_STATISTICS_REQUEST = 'GET_DASHBOARD_STATISTICS_REQUEST';
export const GET_DASHBOARD_STATISTICS_SUCCESS = 'GET_DASHBOARD_STATISTICS_SUCCESS';
export const GET_DASHBOARD_STATISTICS_FAIL = 'GET_DASHBOARD_STATISTICS_FAIL';